### ISSUE TITLE
dragging .miz over MassWaypointEdit.exe didn't work

### ISSUE THREAD

**Issue by derbuur** [Dzsek/DCSMassWaypointEdit#1]
Hi, I tried your program and follow the instruction but when I drag the .miz file over MassWaypointEdit.exe nothing happens.
I have no idea how to debug the problem. Can you give some advises?

**Comment by Dzsek** [comment]
You can try opening up a command prompt in the folder and running MassWaypointEdit.exe from there, and pass the mission file as the first parameters

**Comment by derbuur** [comment]
ok, I found the problem. Your tool needs the framework version 3.1.0 but I have installed the 6.0.6.
Now everything works as intended.
Thanks
