### ISSUE TITLE
Your solution does not write a proper lua table, causing issues in other solutions

### ISSUE THREAD

**Issue by karel26** [Dzsek/DCSMassWaypointEdit#3]
Hey mate,

I am the developer of DCSServerBot, a solution being used by some hundred of DCS servers. This includes solutions to change stuff in missions like weather, etc.

To do so, I parse the mission, which is a large lua table per default and as created by DCS. Now, your solution does not create a lua table but a structure like this:
```lua
mission = {}
mission["requiredModules"] = { }
mission["date"] = { ['Year']=2016,['Day']=21,['Month']=6 }
mission["start_time"] = 28800
mission["maxDictId"] = 12
mission["theatre"] = "Caucasus"
```

the format I and others expect is this
```lua
mission = 
{
    ["requiredModules"] = 
    {
    }, -- end of ["requiredModules"]
    ["date"] = 
    {
        ["Year"] = 1999,
        ["Day"] = 1,
        ["Month"] = 7,
    }, -- end of ["date"]
    ["result"] = 
    {
        ["offline"] = 
  ```
meaning a single lua table to read. My parser expects a table and can't work with mission files like that.
Would you mind changing that in your solution, so that the mission file again is a large lua table? Otherwise, I can not support your solution.

Thanks

Special K

**Comment by Dzsek** [comment]
Try the new version, it should be pretty similar now to EDs original format
